## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/  
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ParquetFiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
